added endpoint resource and added support for Map type
CiscoDevNet/terraform-provider-ise pull request #47
Opened 2024-03-27 20:29 UTC by kuba-mazurkiewicz

added endpoint resource and added support for Map type

2024-03-30 09:38 UTC, danischm requested changes

2024-03-30 09:38 UTC, danischm commented on gen/definitions/endpoint.yaml
> +    example: 3a88eec0-8c00-11e6-996c-525400b48521
Shouldn't we use a `test_value` here?

2024-04-01 19:30 UTC, kuba-mazurkiewicz commented on gen/definitions/endpoint.yaml
> +    example: 3a88eec0-8c00-11e6-996c-525400b48521
done

2024-04-01 19:44 UTC, danischm requested changes

2024-04-01 19:44 UTC, danischm commented on gen/definitions/endpoint.yaml
> +    example: 3a91a150-8c00-11e6-996c-525400b48521
What about this one? Do we already have a resource for this and/or is this a global id?

2024-04-01 20:01 UTC, kuba-mazurkiewicz commented on gen/definitions/endpoint.yaml
> +    example: 3a91a150-8c00-11e6-996c-525400b48521
this one is one of the defaults one which I took. Looks like there is only Get-All and Get-By-Id in ERS API

2024-04-10 11:42 UTC, danischm approved these changes

2024-04-10 11:42 UTC, merged